FROM bioconductor/bioconductor_docker:RELEASE_3_17-R-4.3.0

COPY ./prepare_data /app/prepare_data
COPY ./dependencies /app/dependencies
WORKDIR /app

RUN set -ex 

RUN apt-get update \
    && apt-get install -y \
    cmake \
    git \
    openjdk-11-jre \
    python3-dev \
    python3-pip \
    r-cran-ggplot2 \
    r-cran-optparse \
    && apt-get clean \
    # Delete packages in '/var/lib' to remove side-effects of apt-get update:
    # https://github.com/Bioconductor/bioconductor_docker?tab=readme-ov-file#modifying-the-images
    && rm -rf /var/lib/apt/lists/*

# Install Python and R dependencies
RUN pip3 install --no-cache-dir -r dependencies/requirements-workflow.txt
RUN bash dependencies/r-packages-workflow.sh

# Handle dependency problems related to Java installation:
# https://stackoverflow.com/questions/61815233/install-java-runtime-in-debian-based-docker-image
RUN mkdir -p /usr/share/man/man1 /usr/share/man/man2

# Install C++ and Java dependencies for module detection
WORKDIR /app/prepare_data/workflow/scripts/module_detection

# -- ClusterONE --
RUN wget https://paccanarolab.org/static_content/clusterone/cluster_one-1.0.jar

# -- LazyFox --
RUN git clone https://github.com/TimGarrels/LazyFox \
    && mv LazyFox lazyfoxdir \
    && cd lazyfoxdir \
    && git reset --hard d08f3c084df19bd2a1726159f181bbe3ad6f5bf4 \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make \
    && mv LazyFox ../../LazyFox \
    && cd ../../ \
    && rm -r lazyfoxdir \
    && chmod +x LazyFox

WORKDIR /app/prepare_data/workflow/scripts
ENTRYPOINT ["tail", "-f", "/dev/null"]