FROM tiangolo/uwsgi-nginx-flask:python3.10

COPY . /app
WORKDIR /app

RUN set -ex 

RUN apt-get update \
  && apt-get install -y \
  bedtools \
  cron \
  git \
  python3-dev \
  python3-pip \
  && apt-get clean

# Install dependencies
RUN pip3 install --no-cache-dir -r dependencies/requirements-app.txt \
  && pip3 install --no-cache-dir -r dependencies/requirements-google-api.txt

# Install mcdp2
RUN cd ../ \
  && git clone https://github.com/fmfi-compbio/mcdp2 \
  && cd mcdp2 \
  && git reset --hard fd7c69f5e97db8c1052df859cb02d86533287e64 \
  && pip3 install . \
  && cd ../app

# Run cron jobs
RUN cp cron_jobs/jobs/upload-logs-to-drive /etc/cron.d/upload-logs-to-drive \
  && chmod 0644 /etc/cron.d/upload-logs-to-drive \
  && cron

# Write configuration file
RUN python3 generate_config.py --deployed --latest-version --logging
