FROM tiangolo/uwsgi-nginx-flask:python3.10

COPY . /app
WORKDIR /app

RUN set -ex 

# Signal that deployed version should be used
RUN touch .deploy

RUN apt-get update \
  && apt-get install -y \
  bedtools \
  git \
  python3-dev \
  python3-pip \
  && apt-get clean

# Get latest release version number
RUN pip3 install --no-cache-dir requests \
  && ((echo "import requests"; echo "latest_release = requests.get('https://github.com/bioinfodlsu/rice-pilaf/releases/latest')"; echo "print(latest_release.url.split('/')[-1])") | python3 > .version)
  && pip3 uninstall -y requests

RUN pip3 install --no-cache-dir -r dependencies/requirements-app.txt

# Install mcdp2
RUN cd ../ \
  && git clone https://github.com/fmfi-compbio/mcdp2 \
  && cd mcdp2 \
  && git reset --hard fd7c69f5e97db8c1052df859cb02d86533287e64 \
  && pip3 install . \
  && cd ../app
