FROM python:3.10-bullseye

COPY ./prepare_data /app/prepare_data
COPY ./dependencies /app/dependencies
WORKDIR /app

RUN set -ex 

# For R installation
RUN echo 'deb [trusted=yes] http://cloud.r-project.org/bin/linux/debian bullseye-cran40/' >> /etc/apt/sources.list

RUN apt-get clean \
  && apt-get update \
  && apt-get install -y \
  build-essential \
  cmake \
  bedtools \
  gdebi-core \
  git \
  libcurl4-openssl-dev \
  libffi-dev \
  libfontconfig1-dev \
  libfribidi-dev \
  libharfbuzz-dev \
  libssl-dev \
  libxml2-dev \
  openjdk-11-jre \
  python3-dev \
  python3-pip \
  r-base

# Install Python and R dependencies
RUN pip3 install --no-cache-dir -r dependencies/requirements-workflow.txt
RUN bash dependencies/download-r-packages-workflow.sh

# Handle dependency problems related to Java installation:
# https://stackoverflow.com/questions/61815233/install-java-runtime-in-debian-based-docker-image
RUN mkdir -p /usr/share/man/man1 /usr/share/man/man2

WORKDIR /app/prepare_data/workflow/scripts/module_detection

# Install ClusterONE
RUN wget https://paccanarolab.org/static_content/clusterone/cluster_one-1.0.jar

# Install LazyFox
RUN git clone https://github.com/TimGarrels/LazyFox \
  && mv LazyFox lazyfoxdir \
  && cd lazyfoxdir \
  && git reset --hard d08f3c084df19bd2a1726159f181bbe3ad6f5bf4 \
  && mkdir build \
  && cd build \
  && cmake .. \
  && make \
  && mv LazyFox ../../LazyFox \
  && cd ../../ \
  && rm -r lazyfoxdir \
  && chmod +x LazyFox

WORKDIR /app/prepare_data/workflow/scripts
ENTRYPOINT ["tail", "-f", "/dev/null"]
