#Input and output path
input_data_dir: "../../static"
processed_data_dir: "../../Azu_IR64_ARC_CHAO"
tfbs_dir: "../../static/tfbs"

#Data
#compute whole-genome alignment vs. Nb, for the following genomes
other_refs:
    ["Azu","IR64","ARC","CHAO"]
threads: 1

#Data URLs
assembly_links:
    Nb: "https://riceome.hzau.edu.cn/download/Npb.fasta"
    ARC: "https://riceome.hzau.edu.cn/download/117425.fasta"
    Azu: "https://riceome.hzau.edu.cn/download/Azucena.fasta"
    CHAO: "https://riceome.hzau.edu.cn/download/132278.fasta"
    IR64: "https://riceome.hzau.edu.cn/download/IR64.fasta"
    LIU: "https://riceome.hzau.edu.cn/download/125827.fasta"
    MH63: "https://riceome.hzau.edu.cn/download/MH63RS3.fasta"
    N22: "https://riceome.hzau.edu.cn/download/117534.fasta"
annotation_links:
    Nb: "https://riceome.hzau.edu.cn/download/IRGSPMSU.gff"
    ARC: "https://riceome.hzau.edu.cn/download/117425.gff"
    Azu: "https://riceome.hzau.edu.cn/download/Azucena.gff"
    CHAO: "https://riceome.hzau.edu.cn/download/132278.gff"
    IR64: "https://riceome.hzau.edu.cn/download/IR64.gff"
    LIU: "https://riceome.hzau.edu.cn/download/125827.gff"
    MH63: "https://riceome.hzau.edu.cn/download/MH63RS3.gff"
    N22: "https://riceome.hzau.edu.cn/download/117534.gff"
tfbs_links:
    tf_list: "http://planttfdb.gao-lab.org/download/TF_list/Osj_TF_list.txt.gz"
    promoter_motif: "http://plantregmap.gao-lab.org/download_ftp.php?filepath=08-download/Oryza_sativa_Japonica_Group/binding/TFBS_from_motif_inProm_Osj.gff"
    promoter_motif_CE: "http://plantregmap.gao-lab.org/download_ftp.php?filepath=08-download/Oryza_sativa_Japonica_Group/binding/TFBS_from_motif_CE_inProm_Osj.gff"
    promoter_FunTBFS: "http://plantregmap.gao-lab.org/download_ftp.php?filepath=08-download/Oryza_sativa_Japonica_Group/binding/TFBS_from_FunTFBS_inProm_Osj.gff"
    genome_motif: "http://plantregmap.gao-lab.org/download_ftp.php?filepath=08-download/Oryza_sativa_Japonica_Group/binding/TFBS_from_motif_genome-wide_Osj.gff"
    genome_motif_CE: "http://plantregmap.gao-lab.org/download_ftp.php?filepath=08-download/Oryza_sativa_Japonica_Group/binding/TFBS_from_motif_CE_genome-wide_Osj.gff"
    genome_FunTBFS: "http://plantregmap.gao-lab.org/download_ftp.php?filepath=08-download/Oryza_sativa_Japonica_Group/binding/TFBS_from_FunTFBS_genome-wide_Osj.gff"


# MODULE DETECTION
network_dir: "../../static/app_data/networks"
mod_detect_dir: "../../static/raw_data/network_modules"
network_mod_dir: "../../static/app_data/network_modules"

networks:
    "STRING-Physical": "{network_dir}/STRING-Physical.txt"

get_mod_from_clusterone_path: "scripts/module_util/get-modules-from-clusterone-results.py"

# ClusterOne
clusterone_jar_path: "scripts/module_detection/cluster_one-1.0.jar"
clusterone_min_density:
    30: 0.3
    40: 0.4
    # 50: 0.5 # For Testing - Remove in Actual
    60: 0.6
    # 70: 0.7 # For Testing - Remove in Actual
    90: 0.9

# FOX
wcc_threshold:
    # 1: 0.01 # For Testing - Remove in Actual
    5: 0.05
    20: 0.2
    40: 0.4
    50: 0.5 # For Testing - Remove in Actual
    60: 0.6