on: [push, pull_request]

name: Check code formatting quality

jobs:
    run-black-formatter:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: psf/black@stable
              with:
                  options: "--check --verbose"

    run-isort:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - uses: isort/isort-action@master
              with:
                  requirementsFiles: "dependencies/requirements-app.txt dependencies/requirements-workflow.txt"
