name: Create and publish a Docker image

on:
  create:
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:                                                 # Cannot use env variables inside matrix
        include:
          - dockerfile: Dockerfile-app                        # Change to Dockerfile of app
            image: ghcr.io/bioinfodlsu/rice-pilaf/app         
          - dockerfile: Dockerfile-workflow                   # Change to Dockerfile of workflow
            image: ghcr.io/bioinfodlsu/rice-pilaf/workflow    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha, mode=max
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.image }}:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
