name: Mirror dev to demo branch

on:
    workflow_run:
        workflows: [Check for syntax errors]
        types: [completed]
        branches: [dev]

jobs:
    mirror_job:
        runs-on: ubuntu-latest
        name: Mirror dev branch to demo branch
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - name: Mirror action step
              id: mirror
              uses: google/mirror-branch-action@main
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  source: "dev"
                  dest: "demo"

    on-failure:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
            - run: echo 'The triggering workflow failed'
