name: Publish release 

on: 
  workflow_run:
    workflows: [Delete package versions]
    types: [completed]
    branches: [main]
    
jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: norelease
          
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
