name: Publish release

on:
    push:
        branches: [minor-release, major-release, patch]

jobs:
    release-on-push:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            RELEASE_BODY: "Welcome! RicePilaf is short for Rice Post-GWAS/QTL Analysis dashboard. Ok, so we are not great at acronyms; but like a flavorful rice pilaf that combines many ingredients, this RicePilaf combines information from multiple rice databases to provide insights into your QTL/GWAS loci.\n\n ## Installation and Usage \nPlease visit the [wiki](https://github.com/bioinfodlsu/rice-pilaf/wiki).\n\n ## Changelog\n"
        outputs:
            branch: ${{ github.ref.name }}
        steps:
            - name: Print release branch
              run: echo "${{ github.ref }}"
            - uses: memgonzales/release-on-push-action@master
              if: ${{ github.ref == 'refs/heads/minor-release' }}
              with:
                  bump_version_scheme: minor
                  release_body: ${{ env.RELEASE_BODY }}

            - uses: memgonzales/release-on-push-action@master
              if: ${{ github.ref == 'refs/heads/major-release' }}
              with:
                  bump_version_scheme: major
                  release_body: ${{ env.RELEASE_BODY }}

            - uses: memgonzales/release-on-push-action@master
              if: ${{ github.ref == 'refs/heads/patch' }}
              with:
                  bump_version_scheme: patch
                  release_body: ${{ env.RELEASE_BODY }}

    mirror-release-to-main:
        needs: release-on-push
        name: Mirror release branch to main branch
        runs-on: ubuntu-latest
        outputs:
            branch: ${{ needs.release-on-push.outputs.branch }}
        steps:
            - name: Print branch to be mirrored
              run: echo "${{ needs.release-on-push.outputs.branch }}"
            - name: Mirror action step
              id: mirror
              uses: google/mirror-branch-action@v2.0
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  source: ${{ needs.release-on-push.outputs.branch }}
                  dest: "main"

    delete-release-branch:
        needs: mirror-release-to-main
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        steps:
            - name: Print branch to be deleted
              run: echo "${{ needs.mirror-release-to-main.outputs.branch }}"
            - uses: dawidd6/action-delete-branch@v3
              with:
                  branches: ${{ needs.mirror-release-to-main.outputs.branch }}
