name: Publish minor release

on:
    push:
        branches:
            - minor-release

jobs:
    release-on-push:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        steps:
            - uses: memgonzales/release-on-push-action@master
              with:
                  bump_version_scheme: minor
                  release_body: "## RicePilaf \nWelcome! RicePilaf is short for Rice Post-GWAS/QTL Analysis dashboard. Ok, so we are not great at acronyms; but like a flavorful rice pilaf that combines many ingredients, this RicePilaf combines information from multiple rice databases to provide insights into your QTL/GWAS loci.\n ## Installation and Usage \nPlease visit the [wiki](https://github.com/bioinfodlsu/rice-pilaf/wiki).\n ### Dataset \n Download the dataset needed for the app from here.\n ### Changelog"
